app = "discoverkenyaapi"
primary_region = "jnb"

[env]
  RAILS_ENV = "production"

[experimental]
  allowed_public_ports = [80]

[build]
  builder = "paketobuildpacks/builder:base"

[[services]]
  internal_port = 3000
  processes = ["app"]

  [[services.ports]]
    handlers = ["http"]
    port = 80